---
# This role installs httpd

- name: Install http #changed for loop due to deprecation warning
  yum:
    name:
      - httpd
      - php
      - php-mysql
      - git
    state: present
    autoclean: yes

  

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
  when: sestatus.rc != 0

- name: http service state
  service:
    name: httpd
    state: started
    enabled: yes
