---
# This role installs httpd

- name: Install apache2 #changed for loop due to deprecation warning
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - git
    state: present
    update_cache: yes
    autoclean: yes

- name: enable auth modes on apache2
  apache2_module:
   name: auth_digest
  notify:
   - restart apache2    

#- name: Configure SELinux to allow httpd to connect to remote database
#  seboolean:
#    name: httpd_can_network_connect_db
#    state: true
#    persistent: yes
 # when: sestatus.rc != 0

- name: http service state
  service:
    name: apache2
    state: started
    enabled: yes
