---
# Handlers for common notifications
#Changed the syntax to more yaml like
- name: restart ntp
  service: 
   name: ntpd 
   state: restarted

- name: restart iptables
  service: 
   name: iptables 
   state: restarted
